export declare enum Themes {
  A11yDark = "a11y-dark",
  Blackboard = "blackboard",
  Base16 = "base-16",
  Cobalt = "cobalt",
  DraculaPro = "dracula-pro",
  Duotone = "duotone",
  Hopscotch = "hopscotch",
  Lucario = "lucario",
  Material = "material",
  Monokai = "monokai",
  NightOwl = "night-owl",
  Nord = "nord",
  OceanicNext = "oceanic-next",
  OneLight = "one-light",
  OneDark = "one-dark",
  Panda = "panda",
  Paraiso = "paraiso",
  Seti = "seti",
  ShadesOfPurple = "shades-of-purple",
  Solarized = "solarized",
  Twilight = "twilight",
  Verminal = "verminal",
  VSCode = "vscode",
  Yeti = "yeti",
  Zenburn = "zenburn",
}
export declare enum BackgroundColors {
  Red = "rgba(255, 0, 0, 1)",
  Green = "rgba(0, 255, 0, 1)",
  Blue = "rgba(0, 0, 255, 1)",
  Yellow = "rgba(255, 255, 0, 1)",
  Orange = "rgba(255, 165, 0, 1)",
  Purple = "rgba(128, 0, 128, 1)",
  Cyan = "rgba(0, 255, 255, 1)",
  Magenta = "rgba(255, 0, 255, 1)",
  White = "rgba(255, 255, 255, 1)",
  Black = "rgba(0, 0, 0, 1)",
}
