"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BackgroundColors = exports.Themes = void 0;
var Themes;
(function (Themes) {
  Themes["A11yDark"] = "a11y-dark";
  Themes["Blackboard"] = "blackboard";
  Themes["Base16"] = "base-16";
  Themes["Cobalt"] = "cobalt";
  Themes["DraculaPro"] = "dracula-pro";
  Themes["Duotone"] = "duotone";
  Themes["Hopscotch"] = "hopscotch";
  Themes["Lucario"] = "lucario";
  Themes["Material"] = "material";
  Themes["Monokai"] = "monokai";
  Themes["NightOwl"] = "night-owl";
  Themes["Nord"] = "nord";
  Themes["OceanicNext"] = "oceanic-next";
  Themes["OneLight"] = "one-light";
  Themes["OneDark"] = "one-dark";
  Themes["Panda"] = "panda";
  Themes["Paraiso"] = "paraiso";
  Themes["Seti"] = "seti";
  Themes["ShadesOfPurple"] = "shades-of-purple";
  Themes["Solarized"] = "solarized";
  Themes["Twilight"] = "twilight";
  Themes["Verminal"] = "verminal";
  Themes["VSCode"] = "vscode";
  Themes["Yeti"] = "yeti";
  Themes["Zenburn"] = "zenburn";
})(Themes || (exports.Themes = Themes = {}));
var BackgroundColors;
(function (BackgroundColors) {
  BackgroundColors["Red"] = "rgba(255, 0, 0, 1)";
  BackgroundColors["Green"] = "rgba(0, 255, 0, 1)";
  BackgroundColors["Blue"] = "rgba(0, 0, 255, 1)";
  BackgroundColors["Yellow"] = "rgba(255, 255, 0, 1)";
  BackgroundColors["Orange"] = "rgba(255, 165, 0, 1)";
  BackgroundColors["Purple"] = "rgba(128, 0, 128, 1)";
  BackgroundColors["Cyan"] = "rgba(0, 255, 255, 1)";
  BackgroundColors["Magenta"] = "rgba(255, 0, 255, 1)";
  BackgroundColors["White"] = "rgba(255, 255, 255, 1)";
  BackgroundColors["Black"] = "rgba(0, 0, 0, 1)";
})(BackgroundColors || (exports.BackgroundColors = BackgroundColors = {}));
